//JavaScript 7th Edition
//Final Project

//Die roller, etc
//Author: Alix Burton
//Date:   12/8

//Filename: editions.js

//Sets content of the different editions to constants
const originaledition = [
    "The original D&D was published as a box set in 1974 and features only a handful of the elements for which the game is known today:" +
    "just three character classes (fighting-man, magic-user, and cleric); four races (human, dwarf, elf, and hobbit); only a few monsters; only three alignments (lawful, neutral, and chaotic)."+
    "With a production budget of only $2000 to print a thousand copies, the result has been described as amateurish. Only $100 was budgeted for artwork, and TSR co-founder Gary Gygax pressed "+
    "into service anyone who was willing to help, including local artist Cookie Corey; Greg Bell, a member of Jeff Perren's gaming group; D&D co-creator Dave Arneson; Gygax's wife's half-sister Keenan Powell; "+
    "and fellow TSR co-founder Don Kaye. Each artist was paid $2 for a small piece or $3 for a larger piece, with an identical amount paid as a royalty every time another thousand copies were printed."+
    "The rules assume that players own and play the miniatures wargame Chainmail and use its measurement and combat systems. An optional combat system is included within the rules that later developed into "+
    "the sole combat system of later versions of the game. In addition, the rules presume ownership of Outdoor Survival, a board game by then-unaffiliated company Avalon Hill for outdoor exploration and adventure."+
    "D&D was a radically new gaming concept at the time, and it was difficult for players without prior tabletop wargaming experience to grasp the vague rules. The release of the Greyhawk supplement removed "+
    "the game's dependency on the Chainmail rules, and made it much easier for new, non-wargaming players to grasp the concepts of play. It also inadvertently aided the growth of competing game publishers,"+
    "since just about anyone who grasped the concepts behind the game could write smoother and easier-to-use rules systems and sell them to the growing D&D fanbase (Tunnels & Trolls being the first such)."+
    "Supplements such as Greyhawk, Blackmoor, Eldritch Wizardry and Gods, Demi-Gods & Heroes, published over the next two years, greatly expanded the rules, character classes, monsters and spells."+
    "For example, the original Greyhawk supplement introduced the thief class, and weapon damage varying by weapon (as opposed to character class). In addition, many additions and options were published" +
    "in the magazines The Strategic Review and its successor, The Dragon."
]
const firstedition = ["An updated version of D&D was released between 1977 and 1979 as Advanced Dungeons & Dragons (AD&D). The game rules were reorganized and re-codified across three hardcover rulebooks," +
    "compiled by Gary Gygax, incorporating the original D&D rules and many additions and revisions from supplements and magazine articles. The three core rulebooks are the Monster Manual (1977), the Player's Handbook (1978), "+
    "and the Dungeon Master's Guide (1979). Major additions include classes from supplements like assassin, druid, monk, paladin, and thief, while bard, illusionist, and ranger,which had previously only appeared in "+
    "magazine articles, were added to the core rulebooks. An alignment system with nine alignments is used, rather than the previous three-alignment system in the original D&D rules. Later supplements for AD&D include Deities & Demigods (1980), " +
    "Fiend Folio (another book of monsters produced semi-autonomously in the UK - 1981), Monster Manual II (1983), Oriental Adventures, Unearthed Arcana (1985), which mostly compiles material previously published in Dragon magazine, and others. "
]
const secondedition = ["In 1987, a small team of designers at TSR led by David 'Zeb' Cook began work on the second edition of the AD&D game, which would be completed almost two years later. In 1989, Advanced Dungeons & Dragons 2nd Edition was published, featuring new rules and character classes.By the end of its first decade, AD&D had expanded to several rulebooks, including three collections of monsters (Monster Manual, Monster Manual II, Fiend Folio), and two books governing character skills in wilderness and underground settings. Gygax had already planned a second edition for the game, which would also have been an update of the rules, incorporating the material from Unearthed Arcana, Oriental Adventures, and numerous new innovations from Dragon magazine in the Player's Handbook and Dungeon Master's Guide and would have consolidated the Monster Manual, Monster Manual II and Fiend Folio into one volume. Initially, the 2nd edition was planned to consolidate the game, but more changes were made during development, while still aiming at backwards compatibility with 1st edition." +
    "The release of AD&D 2nd Edition corresponded with important policy changes at TSR. An effort was made to remove aspects of the game which had attracted negative publicity, most notably the removal of all mention of demons and devils, although these fiendish monsters were renamed tanar'ri and baatezu, respectively. Moving away from the moral ambiguity of the 1st edition AD&D, the TSR staff eliminated character classes and races like the assassin and the half-orc, and stressed heroic roleplaying and player teamwork. The target age of the game was also lowered, with most 2nd edition products being aimed primarily at teenagers." +
    "The game was again published as three core rulebooks which incorporated the expansions and revisions which had been published in various supplements over the previous decade. However, the Monster Manual was replaced by the Monstrous Compendium, a loose-leaf binder in which every monster is given a full page of information. It was the intention that packs of new monsters (often setting-specific) could be purchased and added to the binder without the expense or inconvenience of a separate book, allowing the book to be updated and customized as needed. This format proved highly susceptible to wear and tear, however, and presented difficulties in keeping alphabetic order when pages had been printed with monsters on each side. Subsequently, the loose leaf formatting was abandoned and the Compendium as a core book was replaced by single-volume hardcover Monstrous Manual in 1993, collecting popular monsters from the Compendium. The edition also greatly increases the power of dragons, in order to counter the impression of relative weakness of the game's titular monster." +
    "Numerous mechanical changes were made to the game. The combat system was modified. The minimum number required to hit a target uses a mathematical formula in which the defender's armor class (AC) is subtracted from the attacker's THAC0 (To Hit Armor Class '0') number, a simplification of 1st edition's attack matrix tables that had appeared as an optional rule in the 1st edition DMG. Distances are based on in-game units (feet) rather than miniatures-board ones (inches). Critical hits are offered as optional rules." +
    "Character creation is modified in many ways. Demi-human races are given higher level maximums to increase their long-term playability, though they are still restricted in terms of character class flexibility. Character classes are organized into four groups: warrior (fighter, paladin, ranger), wizard (mage, specialist wizard), priest (cleric, druid), and rogue (thief, bard). Assassins and monks were removed from the game as character classes, 'magic-users' are renamed 'mages', illusionists are made into a subtype of the wizard class, along with new classes specializing in the other schools of magic. Proficiencies are officially supported in the Player's Handbook and many supplements, rather than being an optional add-on. Psionics are no longer included in the Player's Handbook, though they later appeared in their own supplement." +
    "Sales of Second Edition's core books were somewhat weaker than First Edition. Combined, the Player's Handbook and Dungeon Master's Guide sold over 400,000 copies in the first year of release, a solid hit, but their lifetime sales were not close to matching the huge success of First Edition.[15] The reasons why are contested. Michael Witwer, a biographer of Gary Gygax, cited the lack of involvement of Gygax and the changes that attempted to avoid controversy.[16] Ben Riggs writes that TSR insiders worried that the word 'Advanced' in the title was scaring off interested newcomers into thinking the product was not for them, and more generally that players of First Edition could simply continue using their old books. Both Witwer and Riggs cite increasing competition from other role-playing games; First Edition was a trailblazer that had carved out an entirely new space, but many more tabletop role-playing games existed by 1989."
]
const thirdedition = ["A major revision of the AD&D rules was released in 2000, the first edition published by Wizards of the Coast, which had acquired TSR in 1997. As the Basic game had been discontinued some years earlier, and the more straightforward title was more marketable, the word 'advanced' was dropped and the new edition was named just Dungeons & Dragons, but still officially referred to as 3rd edition (or 3E for short). It also served as the basis of a broader role-playing system designed around 20-sided dice, called the d20 System.[19] Monte Cook, Jonathan Tweet, and Skip Williams all contributed to the 3rd edition Player's Handbook, Dungeon Master's Guide, and Monster Manual, and then each designer wrote one of the books based on those contributions. In a retrospective on the legacy of Dungeons & Dragons, academic Evan Torner commented that the aim of the designers was to 'simplify and declutter the whole system' – 'D&D 3e and 3.5e bear the influence of Eurogame-style elegant design: that the terminology and choices in the game should be immediately intelligible to all who might play it. Players understanding the game itself got more agency over their PCs' fate'" +
    "The d20 System uses a more unified mechanic than earlier editions, resolving nearly all actions with a d20 die roll plus appropriate modifiers. Modifiers based on ability scores follow a standardized formula. Saving throws are reduced from five categories based on forms of attack to three based on type of defense. Skills and the new system of feats are introduced replacing non-weapon proficiencies, to allow players to further customize their characters. The combat system is greatly expanded, adopting into the core system most of the optional movement and combat system of the 2nd edition Players Option: Combat and Tactics book. Third edition combat allows for a grid system, encouraging highly tactical gameplay and facilitating the use of miniatures. 3rd edition removes previous editions' restrictions on class and race combinations that were intended to track the preferences of the race, and on the level advancement of non-human characters." + 
    "New character options include the new sorcerer class, the thief is renamed rogue (a term that 2nd edition uses to classify both the thief and bard classes), and the prestige classes are introduced, which characters can only enter at higher character levels and if they meet certain character-design prerequisites or fulfill certain in-game goals. Later products include additional and supplementary rules subsystems such as 'epic-level' options for characters above 20th level, as well as a heavily revised treatment of psionics."+
    "The d20 System is presented under the Open Game License, which makes it an open source system for which authors can write new games and game supplements without the need to develop a unique rules system and, more importantly, without the need for direct approval from Wizards of the Coast. This makes it easier to market D&D-compatible content under a broadly recognizable commercial license." +
    "The third edition introduced iconic characters, a group of recurring characters used in illustrations and text explanations. They appear in a variety of Dungeons & Dragons game manuals and tie-in novels."
    ]
const threepointfive = ["In July 2003, a revised version of the 3rd edition D&D rules (termed v. 3.5) was released that incorporated numerous small rule changes, as well as expanding the Dungeon Master's Guide and Monster Manual. This revision was intentionally a small one focusing on addressing common complaints about certain aspects of gameplay, hence the 'half edition' version number. The basic rules are fundamentally the same, only differing in balancing. Many monsters and items are compatible (or even unchanged) between those editions. New spells are added, and numerous changes are made to existing spells, while some spells are removed from the updated Player's Handbook.[22] New feats are added and numerous changes are made to existing feats, while several skills are renamed or merged with other skills. Jackson Haime, for Screen Rant, highlighted that 'Wizards of the Coast printed 12 different core D&D rulebooks between 2000 and 2007. At the same time, they published over 50 supplements that added additional rules, features, races, and magic items to the game'."

]
const fourthedition = ["On August 15, 2007, Wizards of the Coast announced the development of D&D 4th edition. In December 2007, the book Wizards Presents: Races and Classes, the first preview of 4th Edition, was released. This was followed by a second book in January 2008 named Wizards Presents: Worlds and Monsters. The Player's Handbook, Monster Manual, and Dungeon Master's Guide were released in June 2008." +
    "Slashdot reported anger from some players and retailers due to the financial investment in v3.5 and the relatively brief period of time that it had been in publication. Although many players chose to continue playing older editions, or other games such as Pathfinder by Paizo Publishing (itself based on D&D v3.5 via the Open Game License), the initial print run of the 4th edition sold out during preorders, and Wizards of the Coast announced a second print run prior to the game's official release." +
    "Unlike previous editions with just three core rulebooks, 4th edition core rules include multiple volumes of the Player's Handbook, Dungeon Master's Guide, and Monster Manual that were released yearly, with each new book becoming a part of the core. In the first Player's Handbook, the warlock and warlord are included, while the barbarian, bard, druid, sorcerer and monk are not present. Of those classes, the first four were included in Player's Handbook 2, while the monk class appears in Player's Handbook 3. The system of prestige classes is replaced by a system in which characters at 11th level choose a 'paragon path', a specialty based on their class, which defines some of their new powers through 20th level; at level 21, an 'epic destiny' is chosen in a similar manner. Core rules extend to level 30 rather than level 20, bringing 'epic level' play back into the core rules." +
    "Mechanically, 4th edition saw a major overhaul of the game's systems. Changes in spells and other per-encounter resourcing, giving all classes a similar number of at-will, per-encounter and per-day powers. Powers have a wide range of effects including inflicting status effects, creating zones, and forced movement, making combat very tactical for all classes but essentially requiring use of miniatures, reinforced by the use of squares to express distances. Attack rolls, skill checks and defense values all get a bonus equal to one-half level, rounded down, rather than increasing at different rates depending on class or skill point investment. Each skill is either trained (providing a fixed bonus on skill checks, and sometimes allowing more exotic uses for the skills) or untrained, but in either case all characters also receive a bonus to all skill rolls based on level. A system of 'healing surges' and short and long rests are introduced to act as resource management. In 2012, MJ Harnish of Wired commented that it was unclear what the 'lasting legacy' of 4th Edition would be – 'on the positive side, it introduced a new way to play the game, adding streamlined play, improved ease of dungeon master preparation, and character classes that were complementary and balanced. [...] On the other hand, the introduction of 4E caused a major schism in the D&D player base and publishing world alike, one that ultimately lead to the rise of the Pathfinder RPG and a fragmentation of D&D's player base'. In 2024, Torner highlighted that this edition focused on mechanical balance and 'was a purely combat-based miniatures game that afforded each character comparable advantages on the battlefield. This meant a standardization of various components of character building. [...] Fourth edition improved D&D as a tactical combat game by providing PCs clear options in every fight, and a range of options beyond standard sword swinging for' multiple combat rounds. However, Torner viewed the edition as unsuccessful 'despite its emphasis on game balance'."
]
const fifthedition = ["In January 2012, Wizards of the Coast announced that a new edition of the game, at the time referred to as D&D Next, was under development. In direct contrast to the previous editions of the game, D&D Next was developed partly via a public open playtest. An early build of the new edition debuted at the 2012 Dungeons & Dragons Experience event to about 500 fans. Public playtesting began on May 24, 2012, with the final playtest packet released on September 20, 2013." +
    "The 5th edition's Basic Rules, a free PDF containing complete rules for play and a subset of the player and DM content from the core rulebooks, was released on July 3, 2014. The Starter Set was released on July 15, featuring a set of pre-generated characters, a set of instructions for basic play, and the adventure module Lost Mine of Phandelver. The Player's Handbook was released on August 19, 2014. The fifth edition Monster Manual was released on September 30, 2014. The Dungeon Master's Guide was released on December 9, 2014. In January 2016, Wizards released a system reference document for 5th Edition under the Open Game License. This document was later revised and rereleased as System Reference Document 5.1 (SRD 5.1) in May 2016; in January 2023, SRD 5.1 was released under an irrevocable Creative Commons license (CC-BY-4.0)." +
    "The edition returns to having only three core rule books, with the Player's Handbook containing most major races and classes. Since 2014, there have been over twenty 5th edition Dungeon & Dragons books published including new rulebooks, campaign guides and adventure modules. In January 2022, the Expansion Gift Set was released which includes reissued versions of Xanathar's Guide to Everything (2017) and Tasha's Cauldron of Everything (2020), 'the two most significant expansions for Dungeons & Dragons Fifth Edition' along with a new sourcebook, Mordenkainen Presents: Monsters of the Multiverse (2022). This sourcebook updates 'over 250 monster stat blocks alongside 30 playable races pulled from a variety of sources' such as Volo's Guide to Monsters (2016) and Mordenkainen's Tome of Foes (2018). Jackson Haime, for Screen Rant in 2020, compared the large number of rulebooks released for the 3rd/3.5 editions (12 different core rulebooks and over 50 supplements published in seven years) to the number for 5th edition and wrote, "+
    "Dungeons and Dragons 5th edition has been released for almost as long as 3 and 3.5 now, and only has 3 core rulebooks and 4 supplemental books in the style of 3.5'. This edition also has 'setting guides that add some setting-specific rules as opposed to complete supplements that are intended for inclusion with any Dungeons and Dragons game'. Mechanically, 5th edition draws heavily on prior editions, while introducing some new mechanics intended to simplify and streamline play. Skills, weapons, items, saving throws, and other things that characters are trained in now all use a single proficiency bonus that increases as character level increases. Multiple defense values have been removed, returning to a single defense value of armor class and using more traditional saving throws. Saving throws are reworked to be situational checks based on the six core abilities instead of generic d20 rolls. Feats are now optional features that can be taken instead of ability score increases and are reworked to be occasional major upgrades instead of frequent minor upgrades. The 'advantage/disadvantage' mechanic was introduced, streamlining conditional and situational modifiers to a simpler mechanic: rolling two d20s for a situation and taking the higher of the two for 'advantage' and the lower of the two for 'disadvantage' and canceling each other out when more than one apply. The power system of 4th edition was replaced with more traditional class features that are gained as characters level. Clerics, druids, paladins, and wizards prepare known spells using a slightly modified version of the spell preparation system of previous editions. Healing Surges are replaced by Hit Dice, requiring a character to roll a hit die during a short rest instead of healing a flat rate of hit points."
]

//Displays text for selected options from dropdown
function displayText() {
    var dropdown = document.getElementById("books");
    var textDisplay = document.getElementById("feedback");
    var selectedValue = dropdown.value;

    if (selectedValue === "original") {
        textDisplay.innerHTML = originaledition;
    }
    else if (selectedValue === "1e") {
        textDisplay.innerHTML = firstedition;
    }
    else if (selectedValue === "2e") {
        textDisplay.innerHTML = secondedition;
    }
    else if (selectedValue === "3e") {
        textDisplay.innerHTML = thirdedition;
    }
    else if (selectedValue === "3.5e") {
        textDisplay.innerHTML = threepointfive;
    }
    else if (selectedValue === "4e") {
        textDisplay.innerHTML = fourthedition;
    }
    else if (selectedValue === "5e") {
        textDisplay.innerHTML = fifthedition;
    }
    else {
        textDisplay.innerHTML = "Please select another book"
    }
}